[general]
bars = 24
framerate = 60
autosens = 1
sensitivity = 100

[input]
method = pipewire
source = auto

[output]
method = raw
channels = mono
mono_option = average
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 59
frame_delimiter = 10

[smoothing]
noise_reduction = 0.77
