.pragma library

var translations = {
    ru: {
        "Size & Shape": "Размер и форма",
        "Layout": "Компоновка",
        "Appearance": "Внешний вид",
        "Clock": "Часы",
        "Notifications": "Уведомления",
        "Notifications:": "Уведомления:",
        "Modules": "Модули",
        "Animation": "Анимация",
        "Notification panel width:": "Ширина панели уведомлений:",
        "Status panel width:": "Ширина панели статуса:",
        "Expanded panel height:": "Высота раскрытой панели:",
        "Corner radius:": "Скругление углов:",
        "Downloads:": "Загрузки:",
        "Show active jobs / progress": "Показывать активные задачи / прогресс",
        "Screen sharing:": "Демонстрация экрана:",
        "Show capture / presentation state": "Показывать захват / режим презентации",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Показывать результаты сборки (например, JAR собран)",
        "Show incoming notifications": "Показывать входящие уведомления",
        "Body lines:": "Строки текста:",
        "Use 24-hour clock": "Использовать 24-часовой формат",
        "Seconds:": "Секунды:",
        "Show seconds": "Показывать секунды",
        "Date:": "Дата:",
        "Show day and date": "Показывать день и дату",
        "Show:": "Показывать:",
        "CPU usage": "Загрузка CPU",
        "RAM usage": "Использование RAM",
        "CPU temperature": "Температура CPU",
        "FPS counter:": "Счётчик FPS:",
        "FPS style:": "Стиль FPS:",
        "Accent badge (e.g. 60 fps)": "Акцентный значок (например, 60 fps)",
        "Animations:": "Анимации:",
        "Enable transitions and pulses": "Включить переходы и пульсации",
        "Animation speed:": "Скорость анимации:",
        "Plasma theme:": "Тема Plasma:",
        "Use the desktop theme's text and panel colors": "Использовать цвета текста и панели из темы рабочего стола",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Если включено, текст следует цветовой схеме, а пользовательский hex-фон заменяется фоном темы.",
        "Expanded background:": "Фон раскрытой панели:",
        "Fill the big panel (the compact capsule stays transparent)": "Заполнять большую панель (компактная капсула остаётся прозрачной)",
        "Background color:": "Цвет фона:",
        "Custom background (hex):": "Пользовательский фон (hex):",
        "Background opacity:": "Непрозрачность фона:",
        "Border:": "Рамка:",
        "Show a subtle outline": "Показывать тонкий контур",
        "Accent color:": "Акцентный цвет:",
        "Custom accent (hex):": "Пользовательский акцент (hex):",
        "Idle dot color:": "Цвет точки простоя:",
        "Sharing dot color:": "Цвет точки демонстрации:",
        "Separators:": "Разделители:",
        "Show “/” dividers between modules": "Показывать разделители “/” между модулями",
        "Distance from panel:": "Расстояние от панели:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Зазор между маленькой капсулой и большой раскрытой панелью. Увеличьте его, если панель слишком близко к капсуле или перекрывает её.",
        "Notification": "Уведомление",
        "Download active": "Идёт загрузка",
        "Downloads": "Загрузки",
        "Sharing screen": "Демонстрация экрана",
        "Build succeeded": "Сборка выполнена",
        "Build failed": "Сборка не удалась",
        "No title": "Без названия",
        "%1 unread": "%1 непрочитано",
        "New notification": "Новое уведомление",
        "Pomodoro session in progress": "Сеанс Pomodoro выполняется",
        "%1% complete": "Выполнено %1%",
        "No active downloads": "Нет активных загрузок",
        "Connected": "Подключено",
        "Active capture or presentation mode": "Активен захват или режим презентации",
        "success": "успех",
        "failed": "ошибка",
        "Status": "Статус",
        "Island width:": "Ширина острова:",
        "Network speed:": "Скорость сети:",
        "Show speed when there are no notifications": "Показывать скорость, когда нет уведомлений",
        "Network speed": "Скорость сети"
    },
    zh: {
        "Today's notifications": "今日通知",
        "No notifications today": "今天没有通知",
        "Clock:": "时钟：",
        "System": "系统",
        "System:": "系统：",
        "System usage is displayed together with the clock.": "系统占用与时钟同时显示。",
        "Show frames-per-second next to System": "在系统信息旁显示帧率",
        "Match clock font (e.g. 60)": "与时钟字体一致（如 60）",
        "Clock and System are always shown from left to right. Clicking Clock opens KOrganizer; clicking System opens the task manager.": "时钟和系统信息始终从左到右排列。点击时钟打开 KOrganizer，点击系统打开任务管理器。",
        "The compact layout is fixed from left to right as Clock, System (with FPS), Notification.": "紧凑布局固定为从左到右：时钟、系统（含 FPS）、通知。",
        "Size & Shape": "大小和形状",
        "Layout": "布局",
        "Appearance": "外观",
        "Clock": "时钟",
        "Notifications": "通知",
        "Notifications:": "通知：",
        "Modules": "模块",
        "Animation": "动画",
        "Notification panel width:": "通知面板宽度：",
        "Status panel width:": "状态面板宽度：",
        "Expanded panel height:": "展开面板高度：",
        "Corner radius:": "圆角半径：",
        "Downloads:": "下载：",
        "Show active jobs / progress": "显示活动任务 / 进度",
        "Screen sharing:": "屏幕共享：",
        "Show capture / presentation state": "显示捕获 / 演示状态",
        "IntelliJ IDEA:": "IntelliJ IDEA：",
        "Show build results (e.g. JAR build succeeded)": "显示构建结果（例如 JAR 构建成功）",
        "Show incoming notifications": "显示收到的通知",
        "Body lines:": "正文行数：",
        "Use 24-hour clock": "使用 24 小时制",
        "Seconds:": "秒：",
        "Show seconds": "显示秒数",
        "Date:": "日期：",
        "Show day and date": "显示星期和日期",
        "Show:": "显示：",
        "CPU usage": "CPU 使用率",
        "RAM usage": "内存使用率",
        "CPU temperature": "CPU 温度",
        "FPS counter:": "FPS 计数器：",
        "FPS style:": "FPS 样式：",
        "Accent badge (e.g. 60 fps)": "强调徽标（例如 60 fps）",
        "Animations:": "动画：",
        "Enable transitions and pulses": "启用过渡和脉冲效果",
        "Animation speed:": "动画速度：",
        "Plasma theme:": "Plasma 主题：",
        "Use the desktop theme's text and panel colors": "使用桌面主题的文本和面板颜色",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "启用后，文本会跟随配色方案，自定义背景 hex 会被主题背景替代。",
        "Expanded background:": "展开背景：",
        "Fill the big panel (the compact capsule stays transparent)": "填充大面板（紧凑胶囊保持透明）",
        "Background color:": "背景颜色：",
        "Custom background (hex):": "自定义背景（hex）：",
        "Background opacity:": "背景不透明度：",
        "Border:": "边框：",
        "Show a subtle outline": "显示细微描边",
        "Accent color:": "强调色：",
        "Custom accent (hex):": "自定义强调色（hex）：",
        "Idle dot color:": "空闲点颜色：",
        "Sharing dot color:": "共享点颜色：",
        "Separators:": "分隔符：",
        "Show “/” dividers between modules": "在模块之间显示 “/” 分隔符",
        "Distance from panel:": "距面板距离：",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "小胶囊和展开大面板之间的间距。如果面板太靠近或覆盖胶囊，请增大该值。",
        "Notification": "通知",
        "Download active": "下载进行中",
        "Downloads": "下载",
        "Sharing screen": "正在共享屏幕",
        "Build succeeded": "构建成功",
        "Build failed": "构建失败",
        "No title": "无标题",
        "%1 unread": "%1 条未读",
        "New notification": "新通知",
        "Pomodoro session in progress": "番茄钟进行中",
        "%1% complete": "已完成 %1%",
        "No active downloads": "没有活动下载",
        "Connected": "已连接",
        "Active capture or presentation mode": "捕获或演示模式已启用",
        "success": "成功",
        "failed": "失败",
        "Status": "状态",
        "Island width:": "灵动岛宽度:",
        "Network speed:": "网络速度:",
        "Show speed when there are no notifications": "没有通知时显示网速",
        "Network speed": "网络速度"
    },
    ja: {
        "Size & Shape": "サイズと形状",
        "Layout": "レイアウト",
        "Appearance": "外観",
        "Clock": "時計",
        "Notifications": "通知",
        "Notifications:": "通知:",
        "Modules": "モジュール",
        "Animation": "アニメーション",
        "Notification panel width:": "通知パネルの幅:",
        "Status panel width:": "ステータスパネルの幅:",
        "Expanded panel height:": "展開パネルの高さ:",
        "Corner radius:": "角の丸み:",
        "Downloads:": "ダウンロード:",
        "Show active jobs / progress": "実行中のジョブ / 進行状況を表示",
        "Screen sharing:": "画面共有:",
        "Show capture / presentation state": "キャプチャ / プレゼン状態を表示",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "ビルド結果を表示 (例: JAR ビルド成功)",
        "Show incoming notifications": "受信通知を表示",
        "Body lines:": "本文の行数:",
        "Use 24-hour clock": "24時間制を使用",
        "Seconds:": "秒:",
        "Show seconds": "秒を表示",
        "Date:": "日付:",
        "Show day and date": "曜日と日付を表示",
        "Show:": "表示:",
        "CPU usage": "CPU 使用率",
        "RAM usage": "RAM 使用率",
        "CPU temperature": "CPU 温度",
        "FPS counter:": "FPS カウンター:",
        "FPS style:": "FPS スタイル:",
        "Accent badge (e.g. 60 fps)": "アクセントバッジ (例: 60 fps)",
        "Animations:": "アニメーション:",
        "Enable transitions and pulses": "遷移とパルスを有効化",
        "Animation speed:": "アニメーション速度:",
        "Plasma theme:": "Plasma テーマ:",
        "Use the desktop theme's text and panel colors": "デスクトップテーマの文字色とパネル色を使用",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "オンにすると、文字は配色に従い、カスタム背景 hex はテーマ背景に置き換えられます。",
        "Expanded background:": "展開時の背景:",
        "Fill the big panel (the compact capsule stays transparent)": "大きなパネルを塗りつぶす (コンパクトカプセルは透明のまま)",
        "Background color:": "背景色:",
        "Custom background (hex):": "カスタム背景 (hex):",
        "Background opacity:": "背景の不透明度:",
        "Border:": "枠線:",
        "Show a subtle outline": "控えめな輪郭を表示",
        "Accent color:": "アクセント色:",
        "Custom accent (hex):": "カスタムアクセント (hex):",
        "Idle dot color:": "アイドル点の色:",
        "Sharing dot color:": "共有点の色:",
        "Separators:": "区切り:",
        "Show “/” dividers between modules": "モジュール間に “/” 区切りを表示",
        "Distance from panel:": "パネルからの距離:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "小さなカプセルと大きな展開パネルの間隔です。パネルが近すぎたり重なったりする場合は増やしてください。",
        "Notification": "通知",
        "Download active": "ダウンロード中",
        "Downloads": "ダウンロード",
        "Sharing screen": "画面共有中",
        "Build succeeded": "ビルド成功",
        "Build failed": "ビルド失敗",
        "No title": "タイトルなし",
        "%1 unread": "未読 %1 件",
        "New notification": "新しい通知",
        "Pomodoro session in progress": "ポモドーロ実行中",
        "%1% complete": "%1% 完了",
        "No active downloads": "アクティブなダウンロードなし",
        "Connected": "接続済み",
        "Active capture or presentation mode": "キャプチャまたはプレゼンモードが有効",
        "success": "成功",
        "failed": "失敗",
        "Status": "状態",
        "Island width:": "アイランドの幅:",
        "Network speed:": "ネットワーク速度:",
        "Show speed when there are no notifications": "通知がないときに速度を表示",
        "Network speed": "ネットワーク速度"
    },
    de: {
        "Size & Shape": "Größe und Form",
        "Layout": "Layout",
        "Appearance": "Erscheinungsbild",
        "Clock": "Uhr",
        "Notifications": "Benachrichtigungen",
        "Notifications:": "Benachrichtigungen:",
        "Modules": "Module",
        "Animation": "Animation",
        "Notification panel width:": "Breite des Benachrichtigungsfelds:",
        "Status panel width:": "Breite des Statusfelds:",
        "Expanded panel height:": "Höhe des erweiterten Felds:",
        "Corner radius:": "Eckenradius:",
        "Downloads:": "Downloads:",
        "Show active jobs / progress": "Aktive Aufträge / Fortschritt anzeigen",
        "Screen sharing:": "Bildschirmfreigabe:",
        "Show capture / presentation state": "Aufnahme- / Präsentationsstatus anzeigen",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Build-Ergebnisse anzeigen (z. B. JAR-Build erfolgreich)",
        "Show incoming notifications": "Eingehende Benachrichtigungen anzeigen",
        "Body lines:": "Textzeilen:",
        "Use 24-hour clock": "24-Stunden-Format verwenden",
        "Seconds:": "Sekunden:",
        "Show seconds": "Sekunden anzeigen",
        "Date:": "Datum:",
        "Show day and date": "Wochentag und Datum anzeigen",
        "Show:": "Anzeigen:",
        "CPU usage": "CPU-Auslastung",
        "RAM usage": "RAM-Auslastung",
        "CPU temperature": "CPU-Temperatur",
        "FPS counter:": "FPS-Zähler:",
        "FPS style:": "FPS-Stil:",
        "Accent badge (e.g. 60 fps)": "Akzent-Plakette (z. B. 60 fps)",
        "Animations:": "Animationen:",
        "Enable transitions and pulses": "Übergänge und Pulse aktivieren",
        "Animation speed:": "Animationsgeschwindigkeit:",
        "Plasma theme:": "Plasma-Design:",
        "Use the desktop theme's text and panel colors": "Text- und Panel-Farben des Desktop-Designs verwenden",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Wenn aktiviert, folgt der Text dem Farbschema und der benutzerdefinierte Hex-Hintergrund wird durch den Design-Hintergrund ersetzt.",
        "Expanded background:": "Hintergrund im erweiterten Zustand:",
        "Fill the big panel (the compact capsule stays transparent)": "Großes Feld füllen (die kompakte Kapsel bleibt transparent)",
        "Background color:": "Hintergrundfarbe:",
        "Custom background (hex):": "Benutzerdefinierter Hintergrund (hex):",
        "Background opacity:": "Hintergrunddeckkraft:",
        "Border:": "Rahmen:",
        "Show a subtle outline": "Dezente Kontur anzeigen",
        "Accent color:": "Akzentfarbe:",
        "Custom accent (hex):": "Benutzerdefinierter Akzent (hex):",
        "Idle dot color:": "Farbe des Leerlaufpunkts:",
        "Sharing dot color:": "Farbe des Freigabepunkts:",
        "Separators:": "Trenner:",
        "Show “/” dividers between modules": "“/”-Trenner zwischen Modulen anzeigen",
        "Distance from panel:": "Abstand zum Panel:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Abstand zwischen der kleinen Kapsel und dem großen erweiterten Feld. Erhöhen Sie ihn, wenn das Feld zu nah erscheint oder die Kapsel überlappt.",
        "Notification": "Benachrichtigung",
        "Download active": "Download aktiv",
        "Downloads": "Downloads",
        "Sharing screen": "Bildschirm wird geteilt",
        "Build succeeded": "Build erfolgreich",
        "Build failed": "Build fehlgeschlagen",
        "No title": "Kein Titel",
        "%1 unread": "%1 ungelesen",
        "New notification": "Neue Benachrichtigung",
        "Pomodoro session in progress": "Pomodoro-Sitzung läuft",
        "%1% complete": "%1% abgeschlossen",
        "No active downloads": "Keine aktiven Downloads",
        "Connected": "Verbunden",
        "Active capture or presentation mode": "Aktiver Aufnahme- oder Präsentationsmodus",
        "success": "erfolgreich",
        "failed": "fehlgeschlagen",
        "Status": "Status",
        "Island width:": "Inselbreite:",
        "Network speed:": "Netzwerkgeschwindigkeit:",
        "Show speed when there are no notifications": "Geschwindigkeit anzeigen, wenn keine Benachrichtigungen vorliegen",
        "Network speed": "Netzwerkgeschwindigkeit"
    },
    sv: {
        "Size & Shape": "Storlek och form",
        "Layout": "Layout",
        "Appearance": "Utseende",
        "Clock": "Klocka",
        "Notifications": "Aviseringar",
        "Notifications:": "Aviseringar:",
        "Modules": "Moduler",
        "Animation": "Animering",
        "Notification panel width:": "Bredd på aviseringspanelen:",
        "Status panel width:": "Bredd på statuspanelen:",
        "Expanded panel height:": "Höjd på expanderad panel:",
        "Corner radius:": "Hörnradie:",
        "Downloads:": "Hämtningar:",
        "Show active jobs / progress": "Visa aktiva jobb / förlopp",
        "Screen sharing:": "Skärmdelning:",
        "Show capture / presentation state": "Visa inspelnings- / presentationsläge",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Visa byggresultat (t.ex. JAR-bygge lyckades)",
        "Show incoming notifications": "Visa inkommande aviseringar",
        "Body lines:": "Textrader:",
        "Use 24-hour clock": "Använd 24-timmarsklocka",
        "Seconds:": "Sekunder:",
        "Show seconds": "Visa sekunder",
        "Date:": "Datum:",
        "Show day and date": "Visa dag och datum",
        "Show:": "Visa:",
        "CPU usage": "CPU-användning",
        "RAM usage": "RAM-användning",
        "CPU temperature": "CPU-temperatur",
        "FPS counter:": "FPS-räknare:",
        "FPS style:": "FPS-stil:",
        "Accent badge (e.g. 60 fps)": "Accentmärke (t.ex. 60 fps)",
        "Animations:": "Animeringar:",
        "Enable transitions and pulses": "Aktivera övergångar och pulser",
        "Animation speed:": "Animeringshastighet:",
        "Plasma theme:": "Plasma-tema:",
        "Use the desktop theme's text and panel colors": "Använd skrivbordstemats text- och panelfärger",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "När detta är på följer texten ditt färgschema och den anpassade bakgrundens hex-värde ersätts av temabakgrunden.",
        "Expanded background:": "Expanderad bakgrund:",
        "Fill the big panel (the compact capsule stays transparent)": "Fyll den stora panelen (den kompakta kapseln förblir genomskinlig)",
        "Background color:": "Bakgrundsfärg:",
        "Custom background (hex):": "Anpassad bakgrund (hex):",
        "Background opacity:": "Bakgrundens opacitet:",
        "Border:": "Kant:",
        "Show a subtle outline": "Visa en diskret kontur",
        "Accent color:": "Accentfärg:",
        "Custom accent (hex):": "Anpassad accent (hex):",
        "Idle dot color:": "Färg på vilopunkt:",
        "Sharing dot color:": "Färg på delningspunkt:",
        "Separators:": "Avgränsare:",
        "Show “/” dividers between modules": "Visa “/”-avgränsare mellan moduler",
        "Distance from panel:": "Avstånd från panelen:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Mellanrum mellan den lilla kapseln och den stora expanderade panelen. Öka det om panelen ligger för nära eller överlappar kapseln.",
        "Notification": "Avisering",
        "Download active": "Hämtning aktiv",
        "Downloads": "Hämtningar",
        "Sharing screen": "Delar skärm",
        "Build succeeded": "Bygge lyckades",
        "Build failed": "Bygge misslyckades",
        "No title": "Ingen titel",
        "%1 unread": "%1 olästa",
        "New notification": "Ny avisering",
        "Pomodoro session in progress": "Pomodoro-pass pågår",
        "%1% complete": "%1% klart",
        "No active downloads": "Inga aktiva hämtningar",
        "Connected": "Ansluten",
        "Active capture or presentation mode": "Aktivt inspelnings- eller presentationsläge",
        "success": "lyckades",
        "failed": "misslyckades",
        "Status": "Status",
        "Island width:": "Öns bredd:",
        "Network speed:": "Nätverkshastighet:",
        "Show speed when there are no notifications": "Visa hastighet när det inte finns aviseringar",
        "Network speed": "Nätverkshastighet"
    },
    be: {
        "Size & Shape": "Памер і форма",
        "Layout": "Макет",
        "Appearance": "Выгляд",
        "Clock": "Гадзіннік",
        "Notifications": "Апавяшчэнні",
        "Notifications:": "Апавяшчэнні:",
        "Modules": "Модулі",
        "Animation": "Анімацыя",
        "Notification panel width:": "Шырыня панэлі апавяшчэнняў:",
        "Status panel width:": "Шырыня панэлі стану:",
        "Expanded panel height:": "Вышыня разгорнутай панэлі:",
        "Corner radius:": "Радыус вуглоў:",
        "Downloads:": "Спампоўкі:",
        "Show active jobs / progress": "Паказваць актыўныя заданні / прагрэс",
        "Screen sharing:": "Дэманстрацыя экрана:",
        "Show capture / presentation state": "Паказваць стан захопу / прэзентацыі",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Паказваць вынікі зборкі (напрыклад, JAR сабраны)",
        "Show incoming notifications": "Паказваць уваходныя апавяшчэнні",
        "Body lines:": "Радкі тэксту:",
        "Use 24-hour clock": "Выкарыстоўваць 24-гадзінны фармат",
        "Seconds:": "Секунды:",
        "Show seconds": "Паказваць секунды",
        "Date:": "Дата:",
        "Show day and date": "Паказваць дзень і дату",
        "Show:": "Паказваць:",
        "CPU usage": "Выкарыстанне CPU",
        "RAM usage": "Выкарыстанне RAM",
        "CPU temperature": "Тэмпература CPU",
        "FPS counter:": "Лічыльнік FPS:",
        "FPS style:": "Стыль FPS:",
        "Accent badge (e.g. 60 fps)": "Акцэнтны значок (напрыклад, 60 fps)",
        "Animations:": "Анімацыі:",
        "Enable transitions and pulses": "Уключыць пераходы і пульсацыі",
        "Animation speed:": "Хуткасць анімацыі:",
        "Plasma theme:": "Тэма Plasma:",
        "Use the desktop theme's text and panel colors": "Выкарыстоўваць колеры тэксту і панэлі з тэмы працоўнага стала",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Калі ўключана, тэкст адпавядае вашай каляровай схеме, а ўласны hex-фон замяняецца фонам тэмы.",
        "Expanded background:": "Фон разгорнутай панэлі:",
        "Fill the big panel (the compact capsule stays transparent)": "Запаўняць вялікую панэль (кампактная капсула застаецца празрыстай)",
        "Background color:": "Колер фону:",
        "Custom background (hex):": "Уласны фон (hex):",
        "Background opacity:": "Непразрыстасць фону:",
        "Border:": "Мяжа:",
        "Show a subtle outline": "Паказваць тонкі контур",
        "Accent color:": "Акцэнтны колер:",
        "Custom accent (hex):": "Уласны акцэнт (hex):",
        "Idle dot color:": "Колер кропкі прастою:",
        "Sharing dot color:": "Колер кропкі дэманстрацыі:",
        "Separators:": "Раздзяляльнікі:",
        "Show “/” dividers between modules": "Паказваць раздзяляльнікі “/” паміж модулямі",
        "Distance from panel:": "Адлегласць ад панэлі:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Прамежак паміж маленькай капсулай і вялікай разгорнутай панэллю. Павялічце яго, калі панэль занадта блізка або перакрывае капсулу.",
        "Notification": "Апавяшчэнне",
        "Download active": "Спампоўка актыўная",
        "Downloads": "Спампоўкі",
        "Sharing screen": "Дэманстрацыя экрана",
        "Build succeeded": "Зборка паспяховая",
        "Build failed": "Зборка не ўдалася",
        "No title": "Без назвы",
        "%1 unread": "%1 непрачытана",
        "New notification": "Новае апавяшчэнне",
        "Pomodoro session in progress": "Сеанс Pomodoro выконваецца",
        "%1% complete": "Выканана %1%",
        "No active downloads": "Няма актыўных спамповак",
        "Connected": "Падключана",
        "Active capture or presentation mode": "Актыўны захоп або рэжым прэзентацыі",
        "success": "поспех",
        "failed": "памылка",
        "Status": "Стан",
        "Island width:": "Шырыня вострава:",
        "Network speed:": "Хуткасць сеткі:",
        "Show speed when there are no notifications": "Паказваць хуткасць, калі няма апавяшчэнняў",
        "Network speed": "Хуткасць сеткі"
    },
    uk: {
        "Size & Shape": "Розмір і форма",
        "Layout": "Компонування",
        "Appearance": "Вигляд",
        "Clock": "Годинник",
        "Notifications": "Сповіщення",
        "Notifications:": "Сповіщення:",
        "Modules": "Модулі",
        "Animation": "Анімація",
        "Notification panel width:": "Ширина панелі сповіщень:",
        "Status panel width:": "Ширина панелі стану:",
        "Expanded panel height:": "Висота розгорнутої панелі:",
        "Corner radius:": "Радіус кутів:",
        "Downloads:": "Завантаження:",
        "Show active jobs / progress": "Показувати активні завдання / прогрес",
        "Screen sharing:": "Демонстрація екрана:",
        "Show capture / presentation state": "Показувати стан захоплення / презентації",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Показувати результати збірки (наприклад, JAR зібрано)",
        "Show incoming notifications": "Показувати вхідні сповіщення",
        "Body lines:": "Рядки тексту:",
        "Use 24-hour clock": "Використовувати 24-годинний формат",
        "Seconds:": "Секунди:",
        "Show seconds": "Показувати секунди",
        "Date:": "Дата:",
        "Show day and date": "Показувати день і дату",
        "Show:": "Показувати:",
        "CPU usage": "Використання CPU",
        "RAM usage": "Використання RAM",
        "CPU temperature": "Температура CPU",
        "FPS counter:": "Лічильник FPS:",
        "FPS style:": "Стиль FPS:",
        "Accent badge (e.g. 60 fps)": "Акцентний значок (наприклад, 60 fps)",
        "Animations:": "Анімації:",
        "Enable transitions and pulses": "Увімкнути переходи та пульсації",
        "Animation speed:": "Швидкість анімації:",
        "Plasma theme:": "Тема Plasma:",
        "Use the desktop theme's text and panel colors": "Використовувати кольори тексту й панелі з теми робочого стола",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Якщо увімкнено, текст відповідає вашій колірній схемі, а власний hex-фон замінюється фоном теми.",
        "Expanded background:": "Фон розгорнутої панелі:",
        "Fill the big panel (the compact capsule stays transparent)": "Заповнювати велику панель (компактна капсула лишається прозорою)",
        "Background color:": "Колір фону:",
        "Custom background (hex):": "Власний фон (hex):",
        "Background opacity:": "Непрозорість фону:",
        "Border:": "Рамка:",
        "Show a subtle outline": "Показувати тонкий контур",
        "Accent color:": "Акцентний колір:",
        "Custom accent (hex):": "Власний акцент (hex):",
        "Idle dot color:": "Колір точки простою:",
        "Sharing dot color:": "Колір точки демонстрації:",
        "Separators:": "Розділювачі:",
        "Show “/” dividers between modules": "Показувати розділювачі “/” між модулями",
        "Distance from panel:": "Відстань від панелі:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Проміжок між малою капсулою та великою розгорнутою панеллю. Збільште його, якщо панель надто близько або перекриває капсулу.",
        "Notification": "Сповіщення",
        "Download active": "Триває завантаження",
        "Downloads": "Завантаження",
        "Sharing screen": "Демонстрація екрана",
        "Build succeeded": "Збірку виконано",
        "Build failed": "Збірка не вдалася",
        "No title": "Без назви",
        "%1 unread": "%1 непрочитано",
        "New notification": "Нове сповіщення",
        "Pomodoro session in progress": "Сеанс Pomodoro триває",
        "%1% complete": "Виконано %1%",
        "No active downloads": "Немає активних завантажень",
        "Connected": "Підключено",
        "Active capture or presentation mode": "Активне захоплення або режим презентації",
        "success": "успіх",
        "failed": "помилка",
        "Status": "Стан",
        "Island width:": "Ширина острова:",
        "Network speed:": "Швидкість мережі:",
        "Show speed when there are no notifications": "Показувати швидкість, коли немає сповіщень",
        "Network speed": "Швидкість мережі"
    }
};

function language() {
    var name = "en";
    try {
        name = Qt.locale().name.toLowerCase().replace("_", "-");
    } catch (error) {
        return "en";
    }

    if (name.indexOf("zh") === 0) {
        return "zh";
    }

    var shortName = name.split("-")[0];
    return translations[shortName] ? shortName : "en";
}

function t(source) {
    var lang = language();
    return translations[lang] && translations[lang][source] ? translations[lang][source] : source;
}

function tr(source, value) {
    return t(source).replace("%1", value);
}
