.pragma library

var translations = {
    ru: {
        "Size & Shape": "Размер и форма",
        "Layout": "Компоновка",
        "Appearance": "Внешний вид",
        "Clock": "Часы",
        "Notifications": "Уведомления",
        "Notifications:": "Уведомления:",
        "Modules": "Модули",
        "System & FPS": "Система и FPS",
        "Animation": "Анимация",
        "Music panel width:": "Ширина панели музыки:",
        "Notification panel width:": "Ширина панели уведомлений:",
        "Status panel width:": "Ширина панели статуса:",
        "Expanded panel height:": "Высота раскрытой панели:",
        "Corner radius:": "Скругление углов:",
        "Media:": "Медиа:",
        "Now playing / MPRIS": "Сейчас играет / MPRIS",
        "Keyboard layout:": "Раскладка клавиатуры:",
        "Announce layout changes": "Показывать смену раскладки",
        "Downloads:": "Загрузки:",
        "Show active jobs / progress": "Показывать активные задачи / прогресс",
        "Screen sharing:": "Демонстрация экрана:",
        "Show capture / presentation state": "Показывать захват / режим презентации",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Показывать результаты сборки (например, JAR собран)",
        "Show incoming notifications": "Показывать входящие уведомления",
        "Body lines:": "Строки текста:",
        "Format:": "Формат:",
        "Use 24-hour clock": "Использовать 24-часовой формат",
        "Seconds:": "Секунды:",
        "Show seconds": "Показывать секунды",
        "Date:": "Дата:",
        "Show day and date": "Показывать день и дату",
        "System stats:": "Статистика системы:",
        "Alternate the idle clock with system usage": "Чередовать часы простоя со статистикой системы",
        "Show:": "Показывать:",
        "CPU usage": "Загрузка CPU",
        "RAM usage": "Использование RAM",
        "CPU temperature": "Температура CPU",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "Температура скрывается автоматически, если оборудование не предоставляет датчик CPU.",
        "Switch every:": "Переключать каждые:",
        "sec": "с",
        "FPS counter:": "Счётчик FPS:",
        "Permanently show frames-per-second next to the clock": "Всегда показывать кадры в секунду рядом с часами",
        "FPS style:": "Стиль FPS:",
        "Accent badge (e.g. 60 fps)": "Акцентный значок (например, 60 fps)",
        "Match clock font (e.g. 60)": "Как шрифт часов (например, 60)",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "Примечание: счётчик FPS постоянно перерисовывает виджет, что немного увеличивает расход энергии.",
        "Animations:": "Анимации:",
        "Enable transitions and pulses": "Включить переходы и пульсации",
        "Animation speed:": "Скорость анимации:",
        "Plasma theme:": "Тема Plasma:",
        "Use the desktop theme's text and panel colors": "Использовать цвета текста и панели из темы рабочего стола",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Если включено, текст следует цветовой схеме, а пользовательский hex-фон заменяется фоном темы.",
        "Expanded background:": "Фон раскрытой панели:",
        "Fill the big panel (the compact capsule stays transparent)": "Заполнять большую панель (компактная капсула остаётся прозрачной)",
        "Background color:": "Цвет фона:",
        "Custom background (hex):": "Пользовательский фон (hex):",
        "Background opacity:": "Непрозрачность фона:",
        "Border:": "Рамка:",
        "Show a subtle outline": "Показывать тонкий контур",
        "Accent color:": "Акцентный цвет:",
        "Custom accent (hex):": "Пользовательский акцент (hex):",
        "Idle dot color:": "Цвет точки простоя:",
        "Sharing dot color:": "Цвет точки демонстрации:",
        "Compact order:": "Порядок в компактном виде:",
        "Content · Time · FPS": "Содержимое · Время · FPS",
        "Time · Content · FPS": "Время · Содержимое · FPS",
        "Content · FPS · Time": "Содержимое · FPS · Время",
        "FPS · Content · Time": "FPS · Содержимое · Время",
        "Time · FPS · Content": "Время · FPS · Содержимое",
        "FPS · Time · Content": "FPS · Время · Содержимое",
        "Separators:": "Разделители:",
        "Show “/” dividers between modules": "Показывать разделители “/” между модулями",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“Содержимое” — активный элемент: музыка, язык, уведомление, загрузка или статус. Время и счётчик FPS можно разместить до или после него.",
        "Distance from panel:": "Расстояние от панели:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Зазор между маленькой капсулой и большой раскрытой панелью. Увеличьте его, если панель слишком близко к капсуле или перекрывает её.",
        "Music": "Музыка",
        "Notification": "Уведомление",
        "Keyboard layout": "Раскладка клавиатуры",
        "Download active": "Идёт загрузка",
        "Downloads": "Загрузки",
        "Sharing screen": "Демонстрация экрана",
        "Build succeeded": "Сборка выполнена",
        "Build failed": "Сборка не удалась",
        "No title": "Без названия",
        "Media player": "Медиаплеер",
        "%1 unread": "%1 непрочитано",
        "New notification": "Новое уведомление",
        "Volume": "Громкость",
        "Pomodoro session in progress": "Сеанс Pomodoro выполняется",
        "%1% complete": "Выполнено %1%",
        "No active downloads": "Нет активных загрузок",
        "Connected": "Подключено",
        "Active capture or presentation mode": "Активен захват или режим презентации",
        "success": "успех",
        "failed": "ошибка",
        "Status": "Статус"
    },
    zh: {
        "Size & Shape": "大小和形状",
        "Layout": "布局",
        "Appearance": "外观",
        "Clock": "时钟",
        "Notifications": "通知",
        "Notifications:": "通知：",
        "Modules": "模块",
        "System & FPS": "系统和 FPS",
        "Animation": "动画",
        "Music panel width:": "音乐面板宽度：",
        "Notification panel width:": "通知面板宽度：",
        "Status panel width:": "状态面板宽度：",
        "Expanded panel height:": "展开面板高度：",
        "Corner radius:": "圆角半径：",
        "Media:": "媒体：",
        "Now playing / MPRIS": "正在播放 / MPRIS",
        "Keyboard layout:": "键盘布局：",
        "Announce layout changes": "提示布局变化",
        "Downloads:": "下载：",
        "Show active jobs / progress": "显示活动任务 / 进度",
        "Screen sharing:": "屏幕共享：",
        "Show capture / presentation state": "显示捕获 / 演示状态",
        "IntelliJ IDEA:": "IntelliJ IDEA：",
        "Show build results (e.g. JAR build succeeded)": "显示构建结果（例如 JAR 构建成功）",
        "Show incoming notifications": "显示收到的通知",
        "Body lines:": "正文行数：",
        "Format:": "格式：",
        "Use 24-hour clock": "使用 24 小时制",
        "Seconds:": "秒：",
        "Show seconds": "显示秒数",
        "Date:": "日期：",
        "Show day and date": "显示星期和日期",
        "System stats:": "系统统计：",
        "Alternate the idle clock with system usage": "空闲时在时钟和系统使用率之间切换",
        "Show:": "显示：",
        "CPU usage": "CPU 使用率",
        "RAM usage": "内存使用率",
        "CPU temperature": "CPU 温度",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "如果硬件未提供 CPU 传感器，温度会自动隐藏。",
        "Switch every:": "切换间隔：",
        "sec": "秒",
        "FPS counter:": "FPS 计数器：",
        "Permanently show frames-per-second next to the clock": "始终在时钟旁显示每秒帧数",
        "FPS style:": "FPS 样式：",
        "Accent badge (e.g. 60 fps)": "强调徽标（例如 60 fps）",
        "Match clock font (e.g. 60)": "匹配时钟字体（例如 60）",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "注意：FPS 计数器会让小组件持续重绘，因此会稍微增加耗电。",
        "Animations:": "动画：",
        "Enable transitions and pulses": "启用过渡和脉冲效果",
        "Animation speed:": "动画速度：",
        "Plasma theme:": "Plasma 主题：",
        "Use the desktop theme's text and panel colors": "使用桌面主题的文本和面板颜色",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "启用后，文本会跟随配色方案，自定义背景 hex 会被主题背景替代。",
        "Expanded background:": "展开背景：",
        "Fill the big panel (the compact capsule stays transparent)": "填充大面板（紧凑胶囊保持透明）",
        "Background color:": "背景颜色：",
        "Custom background (hex):": "自定义背景（hex）：",
        "Background opacity:": "背景不透明度：",
        "Border:": "边框：",
        "Show a subtle outline": "显示细微描边",
        "Accent color:": "强调色：",
        "Custom accent (hex):": "自定义强调色（hex）：",
        "Idle dot color:": "空闲点颜色：",
        "Sharing dot color:": "共享点颜色：",
        "Compact order:": "紧凑顺序：",
        "Content · Time · FPS": "内容 · 时间 · FPS",
        "Time · Content · FPS": "时间 · 内容 · FPS",
        "Content · FPS · Time": "内容 · FPS · 时间",
        "FPS · Content · Time": "FPS · 内容 · 时间",
        "Time · FPS · Content": "时间 · FPS · 内容",
        "FPS · Time · Content": "FPS · 时间 · 内容",
        "Separators:": "分隔符：",
        "Show “/” dividers between modules": "在模块之间显示 “/” 分隔符",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“内容” 是活动项目：音乐、语言、通知、下载或状态。时间和 FPS 计数器可放在它之前或之后。",
        "Distance from panel:": "距面板距离：",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "小胶囊和展开大面板之间的间距。如果面板太靠近或覆盖胶囊，请增大该值。",
        "Music": "音乐",
        "Notification": "通知",
        "Keyboard layout": "键盘布局",
        "Download active": "下载进行中",
        "Downloads": "下载",
        "Sharing screen": "正在共享屏幕",
        "Build succeeded": "构建成功",
        "Build failed": "构建失败",
        "No title": "无标题",
        "Media player": "媒体播放器",
        "%1 unread": "%1 条未读",
        "New notification": "新通知",
        "Volume": "音量",
        "Pomodoro session in progress": "番茄钟进行中",
        "%1% complete": "已完成 %1%",
        "No active downloads": "没有活动下载",
        "Connected": "已连接",
        "Active capture or presentation mode": "捕获或演示模式已启用",
        "success": "成功",
        "failed": "失败",
        "Status": "状态"
    },
    ja: {
        "Size & Shape": "サイズと形状",
        "Layout": "レイアウト",
        "Appearance": "外観",
        "Clock": "時計",
        "Notifications": "通知",
        "Notifications:": "通知:",
        "Modules": "モジュール",
        "System & FPS": "システムと FPS",
        "Animation": "アニメーション",
        "Music panel width:": "音楽パネルの幅:",
        "Notification panel width:": "通知パネルの幅:",
        "Status panel width:": "ステータスパネルの幅:",
        "Expanded panel height:": "展開パネルの高さ:",
        "Corner radius:": "角の丸み:",
        "Media:": "メディア:",
        "Now playing / MPRIS": "再生中 / MPRIS",
        "Keyboard layout:": "キーボード配列:",
        "Announce layout changes": "配列変更を表示",
        "Downloads:": "ダウンロード:",
        "Show active jobs / progress": "実行中のジョブ / 進行状況を表示",
        "Screen sharing:": "画面共有:",
        "Show capture / presentation state": "キャプチャ / プレゼン状態を表示",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "ビルド結果を表示 (例: JAR ビルド成功)",
        "Show incoming notifications": "受信通知を表示",
        "Body lines:": "本文の行数:",
        "Format:": "形式:",
        "Use 24-hour clock": "24時間制を使用",
        "Seconds:": "秒:",
        "Show seconds": "秒を表示",
        "Date:": "日付:",
        "Show day and date": "曜日と日付を表示",
        "System stats:": "システム統計:",
        "Alternate the idle clock with system usage": "アイドル時に時計とシステム使用率を交互に表示",
        "Show:": "表示:",
        "CPU usage": "CPU 使用率",
        "RAM usage": "RAM 使用率",
        "CPU temperature": "CPU 温度",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "ハードウェアが CPU センサーを公開していない場合、温度は自動的に非表示になります。",
        "Switch every:": "切り替え間隔:",
        "sec": "秒",
        "FPS counter:": "FPS カウンター:",
        "Permanently show frames-per-second next to the clock": "時計の横に常に FPS を表示",
        "FPS style:": "FPS スタイル:",
        "Accent badge (e.g. 60 fps)": "アクセントバッジ (例: 60 fps)",
        "Match clock font (e.g. 60)": "時計のフォントに合わせる (例: 60)",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "注: FPS メーターはウィジェットを継続的に再描画するため、少し多く電力を消費します。",
        "Animations:": "アニメーション:",
        "Enable transitions and pulses": "遷移とパルスを有効化",
        "Animation speed:": "アニメーション速度:",
        "Plasma theme:": "Plasma テーマ:",
        "Use the desktop theme's text and panel colors": "デスクトップテーマの文字色とパネル色を使用",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "オンにすると、文字は配色に従い、カスタム背景 hex はテーマ背景に置き換えられます。",
        "Expanded background:": "展開時の背景:",
        "Fill the big panel (the compact capsule stays transparent)": "大きなパネルを塗りつぶす (コンパクトカプセルは透明のまま)",
        "Background color:": "背景色:",
        "Custom background (hex):": "カスタム背景 (hex):",
        "Background opacity:": "背景の不透明度:",
        "Border:": "枠線:",
        "Show a subtle outline": "控えめな輪郭を表示",
        "Accent color:": "アクセント色:",
        "Custom accent (hex):": "カスタムアクセント (hex):",
        "Idle dot color:": "アイドル点の色:",
        "Sharing dot color:": "共有点の色:",
        "Compact order:": "コンパクト表示の順序:",
        "Content · Time · FPS": "内容 · 時刻 · FPS",
        "Time · Content · FPS": "時刻 · 内容 · FPS",
        "Content · FPS · Time": "内容 · FPS · 時刻",
        "FPS · Content · Time": "FPS · 内容 · 時刻",
        "Time · FPS · Content": "時刻 · FPS · 内容",
        "FPS · Time · Content": "FPS · 時刻 · 内容",
        "Separators:": "区切り:",
        "Show “/” dividers between modules": "モジュール間に “/” 区切りを表示",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“内容” は音楽、言語、通知、ダウンロード、状態などのアクティブ項目です。時刻と FPS カウンターはその前後に配置できます。",
        "Distance from panel:": "パネルからの距離:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "小さなカプセルと大きな展開パネルの間隔です。パネルが近すぎたり重なったりする場合は増やしてください。",
        "Music": "音楽",
        "Notification": "通知",
        "Keyboard layout": "キーボード配列",
        "Download active": "ダウンロード中",
        "Downloads": "ダウンロード",
        "Sharing screen": "画面共有中",
        "Build succeeded": "ビルド成功",
        "Build failed": "ビルド失敗",
        "No title": "タイトルなし",
        "Media player": "メディアプレーヤー",
        "%1 unread": "未読 %1 件",
        "New notification": "新しい通知",
        "Volume": "音量",
        "Pomodoro session in progress": "ポモドーロ実行中",
        "%1% complete": "%1% 完了",
        "No active downloads": "アクティブなダウンロードなし",
        "Connected": "接続済み",
        "Active capture or presentation mode": "キャプチャまたはプレゼンモードが有効",
        "success": "成功",
        "failed": "失敗",
        "Status": "状態"
    },
    de: {
        "Size & Shape": "Größe und Form",
        "Layout": "Layout",
        "Appearance": "Erscheinungsbild",
        "Clock": "Uhr",
        "Notifications": "Benachrichtigungen",
        "Notifications:": "Benachrichtigungen:",
        "Modules": "Module",
        "System & FPS": "System und FPS",
        "Animation": "Animation",
        "Music panel width:": "Breite des Musikfelds:",
        "Notification panel width:": "Breite des Benachrichtigungsfelds:",
        "Status panel width:": "Breite des Statusfelds:",
        "Expanded panel height:": "Höhe des erweiterten Felds:",
        "Corner radius:": "Eckenradius:",
        "Media:": "Medien:",
        "Now playing / MPRIS": "Aktuelle Wiedergabe / MPRIS",
        "Keyboard layout:": "Tastaturbelegung:",
        "Announce layout changes": "Änderungen der Belegung anzeigen",
        "Downloads:": "Downloads:",
        "Show active jobs / progress": "Aktive Aufträge / Fortschritt anzeigen",
        "Screen sharing:": "Bildschirmfreigabe:",
        "Show capture / presentation state": "Aufnahme- / Präsentationsstatus anzeigen",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Build-Ergebnisse anzeigen (z. B. JAR-Build erfolgreich)",
        "Show incoming notifications": "Eingehende Benachrichtigungen anzeigen",
        "Body lines:": "Textzeilen:",
        "Format:": "Format:",
        "Use 24-hour clock": "24-Stunden-Format verwenden",
        "Seconds:": "Sekunden:",
        "Show seconds": "Sekunden anzeigen",
        "Date:": "Datum:",
        "Show day and date": "Wochentag und Datum anzeigen",
        "System stats:": "Systemstatistiken:",
        "Alternate the idle clock with system usage": "Uhr im Leerlauf mit Systemauslastung abwechseln",
        "Show:": "Anzeigen:",
        "CPU usage": "CPU-Auslastung",
        "RAM usage": "RAM-Auslastung",
        "CPU temperature": "CPU-Temperatur",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "Die Temperatur wird automatisch ausgeblendet, wenn die Hardware keinen CPU-Sensor bereitstellt.",
        "Switch every:": "Wechsel alle:",
        "sec": "s",
        "FPS counter:": "FPS-Zähler:",
        "Permanently show frames-per-second next to the clock": "Bilder pro Sekunde dauerhaft neben der Uhr anzeigen",
        "FPS style:": "FPS-Stil:",
        "Accent badge (e.g. 60 fps)": "Akzent-Plakette (z. B. 60 fps)",
        "Match clock font (e.g. 60)": "Uhrschrift übernehmen (z. B. 60)",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "Hinweis: Der FPS-Zähler lässt das Widget ständig neu zeichnen, was etwas mehr Energie verbraucht.",
        "Animations:": "Animationen:",
        "Enable transitions and pulses": "Übergänge und Pulse aktivieren",
        "Animation speed:": "Animationsgeschwindigkeit:",
        "Plasma theme:": "Plasma-Design:",
        "Use the desktop theme's text and panel colors": "Text- und Panel-Farben des Desktop-Designs verwenden",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Wenn aktiviert, folgt der Text dem Farbschema und der benutzerdefinierte Hex-Hintergrund wird durch den Design-Hintergrund ersetzt.",
        "Expanded background:": "Hintergrund im erweiterten Zustand:",
        "Fill the big panel (the compact capsule stays transparent)": "Großes Feld füllen (die kompakte Kapsel bleibt transparent)",
        "Background color:": "Hintergrundfarbe:",
        "Custom background (hex):": "Benutzerdefinierter Hintergrund (hex):",
        "Background opacity:": "Hintergrunddeckkraft:",
        "Border:": "Rahmen:",
        "Show a subtle outline": "Dezente Kontur anzeigen",
        "Accent color:": "Akzentfarbe:",
        "Custom accent (hex):": "Benutzerdefinierter Akzent (hex):",
        "Idle dot color:": "Farbe des Leerlaufpunkts:",
        "Sharing dot color:": "Farbe des Freigabepunkts:",
        "Compact order:": "Reihenfolge im Kompaktmodus:",
        "Content · Time · FPS": "Inhalt · Zeit · FPS",
        "Time · Content · FPS": "Zeit · Inhalt · FPS",
        "Content · FPS · Time": "Inhalt · FPS · Zeit",
        "FPS · Content · Time": "FPS · Inhalt · Zeit",
        "Time · FPS · Content": "Zeit · FPS · Inhalt",
        "FPS · Time · Content": "FPS · Zeit · Inhalt",
        "Separators:": "Trenner:",
        "Show “/” dividers between modules": "“/”-Trenner zwischen Modulen anzeigen",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“Inhalt” ist das aktive Element: Musik, Sprache, Benachrichtigung, Download oder Status. Uhrzeit und FPS-Zähler können davor oder dahinter stehen.",
        "Distance from panel:": "Abstand zum Panel:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Abstand zwischen der kleinen Kapsel und dem großen erweiterten Feld. Erhöhen Sie ihn, wenn das Feld zu nah erscheint oder die Kapsel überlappt.",
        "Music": "Musik",
        "Notification": "Benachrichtigung",
        "Keyboard layout": "Tastaturbelegung",
        "Download active": "Download aktiv",
        "Downloads": "Downloads",
        "Sharing screen": "Bildschirm wird geteilt",
        "Build succeeded": "Build erfolgreich",
        "Build failed": "Build fehlgeschlagen",
        "No title": "Kein Titel",
        "Media player": "Medienplayer",
        "%1 unread": "%1 ungelesen",
        "New notification": "Neue Benachrichtigung",
        "Volume": "Lautstärke",
        "Pomodoro session in progress": "Pomodoro-Sitzung läuft",
        "%1% complete": "%1% abgeschlossen",
        "No active downloads": "Keine aktiven Downloads",
        "Connected": "Verbunden",
        "Active capture or presentation mode": "Aktiver Aufnahme- oder Präsentationsmodus",
        "success": "erfolgreich",
        "failed": "fehlgeschlagen",
        "Status": "Status"
    },
    sv: {
        "Size & Shape": "Storlek och form",
        "Layout": "Layout",
        "Appearance": "Utseende",
        "Clock": "Klocka",
        "Notifications": "Aviseringar",
        "Notifications:": "Aviseringar:",
        "Modules": "Moduler",
        "System & FPS": "System och FPS",
        "Animation": "Animering",
        "Music panel width:": "Bredd på musikpanelen:",
        "Notification panel width:": "Bredd på aviseringspanelen:",
        "Status panel width:": "Bredd på statuspanelen:",
        "Expanded panel height:": "Höjd på expanderad panel:",
        "Corner radius:": "Hörnradie:",
        "Media:": "Media:",
        "Now playing / MPRIS": "Spelas nu / MPRIS",
        "Keyboard layout:": "Tangentbordslayout:",
        "Announce layout changes": "Visa layoutändringar",
        "Downloads:": "Hämtningar:",
        "Show active jobs / progress": "Visa aktiva jobb / förlopp",
        "Screen sharing:": "Skärmdelning:",
        "Show capture / presentation state": "Visa inspelnings- / presentationsläge",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Visa byggresultat (t.ex. JAR-bygge lyckades)",
        "Show incoming notifications": "Visa inkommande aviseringar",
        "Body lines:": "Textrader:",
        "Format:": "Format:",
        "Use 24-hour clock": "Använd 24-timmarsklocka",
        "Seconds:": "Sekunder:",
        "Show seconds": "Visa sekunder",
        "Date:": "Datum:",
        "Show day and date": "Visa dag och datum",
        "System stats:": "Systemstatistik:",
        "Alternate the idle clock with system usage": "Växla viloklockan med systemanvändning",
        "Show:": "Visa:",
        "CPU usage": "CPU-användning",
        "RAM usage": "RAM-användning",
        "CPU temperature": "CPU-temperatur",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "Temperaturen döljs automatiskt om maskinvaran inte exponerar en CPU-sensor.",
        "Switch every:": "Växla var:",
        "sec": "s",
        "FPS counter:": "FPS-räknare:",
        "Permanently show frames-per-second next to the clock": "Visa alltid bildrutor per sekund bredvid klockan",
        "FPS style:": "FPS-stil:",
        "Accent badge (e.g. 60 fps)": "Accentmärke (t.ex. 60 fps)",
        "Match clock font (e.g. 60)": "Matcha klockans teckensnitt (t.ex. 60)",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "Obs: FPS-mätaren gör att widgeten ritas om kontinuerligt, vilket drar lite mer ström.",
        "Animations:": "Animeringar:",
        "Enable transitions and pulses": "Aktivera övergångar och pulser",
        "Animation speed:": "Animeringshastighet:",
        "Plasma theme:": "Plasma-tema:",
        "Use the desktop theme's text and panel colors": "Använd skrivbordstemats text- och panelfärger",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "När detta är på följer texten ditt färgschema och den anpassade bakgrundens hex-värde ersätts av temabakgrunden.",
        "Expanded background:": "Expanderad bakgrund:",
        "Fill the big panel (the compact capsule stays transparent)": "Fyll den stora panelen (den kompakta kapseln förblir genomskinlig)",
        "Background color:": "Bakgrundsfärg:",
        "Custom background (hex):": "Anpassad bakgrund (hex):",
        "Background opacity:": "Bakgrundens opacitet:",
        "Border:": "Kant:",
        "Show a subtle outline": "Visa en diskret kontur",
        "Accent color:": "Accentfärg:",
        "Custom accent (hex):": "Anpassad accent (hex):",
        "Idle dot color:": "Färg på vilopunkt:",
        "Sharing dot color:": "Färg på delningspunkt:",
        "Compact order:": "Kompakt ordning:",
        "Content · Time · FPS": "Innehåll · Tid · FPS",
        "Time · Content · FPS": "Tid · Innehåll · FPS",
        "Content · FPS · Time": "Innehåll · FPS · Tid",
        "FPS · Content · Time": "FPS · Innehåll · Tid",
        "Time · FPS · Content": "Tid · FPS · Innehåll",
        "FPS · Time · Content": "FPS · Tid · Innehåll",
        "Separators:": "Avgränsare:",
        "Show “/” dividers between modules": "Visa “/”-avgränsare mellan moduler",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“Innehåll” är det aktiva objektet: musik, språk, avisering, hämtning eller status. Tid och FPS-räknaren kan placeras före eller efter det.",
        "Distance from panel:": "Avstånd från panelen:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Mellanrum mellan den lilla kapseln och den stora expanderade panelen. Öka det om panelen ligger för nära eller överlappar kapseln.",
        "Music": "Musik",
        "Notification": "Avisering",
        "Keyboard layout": "Tangentbordslayout",
        "Download active": "Hämtning aktiv",
        "Downloads": "Hämtningar",
        "Sharing screen": "Delar skärm",
        "Build succeeded": "Bygge lyckades",
        "Build failed": "Bygge misslyckades",
        "No title": "Ingen titel",
        "Media player": "Mediaspelare",
        "%1 unread": "%1 olästa",
        "New notification": "Ny avisering",
        "Volume": "Volym",
        "Pomodoro session in progress": "Pomodoro-pass pågår",
        "%1% complete": "%1% klart",
        "No active downloads": "Inga aktiva hämtningar",
        "Connected": "Ansluten",
        "Active capture or presentation mode": "Aktivt inspelnings- eller presentationsläge",
        "success": "lyckades",
        "failed": "misslyckades",
        "Status": "Status"
    },
    be: {
        "Size & Shape": "Памер і форма",
        "Layout": "Макет",
        "Appearance": "Выгляд",
        "Clock": "Гадзіннік",
        "Notifications": "Апавяшчэнні",
        "Notifications:": "Апавяшчэнні:",
        "Modules": "Модулі",
        "System & FPS": "Сістэма і FPS",
        "Animation": "Анімацыя",
        "Music panel width:": "Шырыня панэлі музыкі:",
        "Notification panel width:": "Шырыня панэлі апавяшчэнняў:",
        "Status panel width:": "Шырыня панэлі стану:",
        "Expanded panel height:": "Вышыня разгорнутай панэлі:",
        "Corner radius:": "Радыус вуглоў:",
        "Media:": "Медыя:",
        "Now playing / MPRIS": "Цяпер прайграецца / MPRIS",
        "Keyboard layout:": "Раскладка клавіятуры:",
        "Announce layout changes": "Паказваць змены раскладкі",
        "Downloads:": "Спампоўкі:",
        "Show active jobs / progress": "Паказваць актыўныя заданні / прагрэс",
        "Screen sharing:": "Дэманстрацыя экрана:",
        "Show capture / presentation state": "Паказваць стан захопу / прэзентацыі",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Паказваць вынікі зборкі (напрыклад, JAR сабраны)",
        "Show incoming notifications": "Паказваць уваходныя апавяшчэнні",
        "Body lines:": "Радкі тэксту:",
        "Format:": "Фармат:",
        "Use 24-hour clock": "Выкарыстоўваць 24-гадзінны фармат",
        "Seconds:": "Секунды:",
        "Show seconds": "Паказваць секунды",
        "Date:": "Дата:",
        "Show day and date": "Паказваць дзень і дату",
        "System stats:": "Статыстыка сістэмы:",
        "Alternate the idle clock with system usage": "Чаргаваць гадзіннік прастою з выкарыстаннем сістэмы",
        "Show:": "Паказваць:",
        "CPU usage": "Выкарыстанне CPU",
        "RAM usage": "Выкарыстанне RAM",
        "CPU temperature": "Тэмпература CPU",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "Тэмпература аўтаматычна хаваецца, калі абсталяванне не дае датчык CPU.",
        "Switch every:": "Пераключаць кожныя:",
        "sec": "с",
        "FPS counter:": "Лічыльнік FPS:",
        "Permanently show frames-per-second next to the clock": "Пастаянна паказваць кадры ў секунду побач з гадзіннікам",
        "FPS style:": "Стыль FPS:",
        "Accent badge (e.g. 60 fps)": "Акцэнтны значок (напрыклад, 60 fps)",
        "Match clock font (e.g. 60)": "Як шрыфт гадзінніка (напрыклад, 60)",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "Заўвага: лічыльнік FPS пастаянна перамалёўвае віджэт, таму спажывае крыху больш энергіі.",
        "Animations:": "Анімацыі:",
        "Enable transitions and pulses": "Уключыць пераходы і пульсацыі",
        "Animation speed:": "Хуткасць анімацыі:",
        "Plasma theme:": "Тэма Plasma:",
        "Use the desktop theme's text and panel colors": "Выкарыстоўваць колеры тэксту і панэлі з тэмы працоўнага стала",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Калі ўключана, тэкст адпавядае вашай каляровай схеме, а ўласны hex-фон замяняецца фонам тэмы.",
        "Expanded background:": "Фон разгорнутай панэлі:",
        "Fill the big panel (the compact capsule stays transparent)": "Запаўняць вялікую панэль (кампактная капсула застаецца празрыстай)",
        "Background color:": "Колер фону:",
        "Custom background (hex):": "Уласны фон (hex):",
        "Background opacity:": "Непразрыстасць фону:",
        "Border:": "Мяжа:",
        "Show a subtle outline": "Паказваць тонкі контур",
        "Accent color:": "Акцэнтны колер:",
        "Custom accent (hex):": "Уласны акцэнт (hex):",
        "Idle dot color:": "Колер кропкі прастою:",
        "Sharing dot color:": "Колер кропкі дэманстрацыі:",
        "Compact order:": "Парадак у кампактным выглядзе:",
        "Content · Time · FPS": "Змест · Час · FPS",
        "Time · Content · FPS": "Час · Змест · FPS",
        "Content · FPS · Time": "Змест · FPS · Час",
        "FPS · Content · Time": "FPS · Змест · Час",
        "Time · FPS · Content": "Час · FPS · Змест",
        "FPS · Time · Content": "FPS · Час · Змест",
        "Separators:": "Раздзяляльнікі:",
        "Show “/” dividers between modules": "Паказваць раздзяляльнікі “/” паміж модулямі",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“Змест” — актыўны элемент: музыка, мова, апавяшчэнне, спампоўка або стан. Час і лічыльнік FPS можна размясціць да або пасля яго.",
        "Distance from panel:": "Адлегласць ад панэлі:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Прамежак паміж маленькай капсулай і вялікай разгорнутай панэллю. Павялічце яго, калі панэль занадта блізка або перакрывае капсулу.",
        "Music": "Музыка",
        "Notification": "Апавяшчэнне",
        "Keyboard layout": "Раскладка клавіятуры",
        "Download active": "Спампоўка актыўная",
        "Downloads": "Спампоўкі",
        "Sharing screen": "Дэманстрацыя экрана",
        "Build succeeded": "Зборка паспяховая",
        "Build failed": "Зборка не ўдалася",
        "No title": "Без назвы",
        "Media player": "Медыяпрайгравальнік",
        "%1 unread": "%1 непрачытана",
        "New notification": "Новае апавяшчэнне",
        "Volume": "Гучнасць",
        "Pomodoro session in progress": "Сеанс Pomodoro выконваецца",
        "%1% complete": "Выканана %1%",
        "No active downloads": "Няма актыўных спамповак",
        "Connected": "Падключана",
        "Active capture or presentation mode": "Актыўны захоп або рэжым прэзентацыі",
        "success": "поспех",
        "failed": "памылка",
        "Status": "Стан"
    },
    uk: {
        "Size & Shape": "Розмір і форма",
        "Layout": "Компонування",
        "Appearance": "Вигляд",
        "Clock": "Годинник",
        "Notifications": "Сповіщення",
        "Notifications:": "Сповіщення:",
        "Modules": "Модулі",
        "System & FPS": "Система і FPS",
        "Animation": "Анімація",
        "Music panel width:": "Ширина панелі музики:",
        "Notification panel width:": "Ширина панелі сповіщень:",
        "Status panel width:": "Ширина панелі стану:",
        "Expanded panel height:": "Висота розгорнутої панелі:",
        "Corner radius:": "Радіус кутів:",
        "Media:": "Медіа:",
        "Now playing / MPRIS": "Зараз відтворюється / MPRIS",
        "Keyboard layout:": "Розкладка клавіатури:",
        "Announce layout changes": "Показувати зміну розкладки",
        "Downloads:": "Завантаження:",
        "Show active jobs / progress": "Показувати активні завдання / прогрес",
        "Screen sharing:": "Демонстрація екрана:",
        "Show capture / presentation state": "Показувати стан захоплення / презентації",
        "IntelliJ IDEA:": "IntelliJ IDEA:",
        "Show build results (e.g. JAR build succeeded)": "Показувати результати збірки (наприклад, JAR зібрано)",
        "Show incoming notifications": "Показувати вхідні сповіщення",
        "Body lines:": "Рядки тексту:",
        "Format:": "Формат:",
        "Use 24-hour clock": "Використовувати 24-годинний формат",
        "Seconds:": "Секунди:",
        "Show seconds": "Показувати секунди",
        "Date:": "Дата:",
        "Show day and date": "Показувати день і дату",
        "System stats:": "Статистика системи:",
        "Alternate the idle clock with system usage": "Чергувати годинник простою зі статистикою системи",
        "Show:": "Показувати:",
        "CPU usage": "Використання CPU",
        "RAM usage": "Використання RAM",
        "CPU temperature": "Температура CPU",
        "Temperature is hidden automatically if your hardware doesn't expose a CPU sensor.": "Температура автоматично приховується, якщо обладнання не надає датчик CPU.",
        "Switch every:": "Перемикати кожні:",
        "sec": "с",
        "FPS counter:": "Лічильник FPS:",
        "Permanently show frames-per-second next to the clock": "Постійно показувати кадри за секунду поруч із годинником",
        "FPS style:": "Стиль FPS:",
        "Accent badge (e.g. 60 fps)": "Акцентний значок (наприклад, 60 fps)",
        "Match clock font (e.g. 60)": "Як шрифт годинника (наприклад, 60)",
        "Note: the FPS meter keeps the widget repainting continuously, which uses a little more power.": "Примітка: лічильник FPS постійно перемальовує віджет, що трохи збільшує споживання енергії.",
        "Animations:": "Анімації:",
        "Enable transitions and pulses": "Увімкнути переходи та пульсації",
        "Animation speed:": "Швидкість анімації:",
        "Plasma theme:": "Тема Plasma:",
        "Use the desktop theme's text and panel colors": "Використовувати кольори тексту й панелі з теми робочого стола",
        "When on, text follows your color scheme and the custom background hex is replaced by the theme background.": "Якщо увімкнено, текст відповідає вашій колірній схемі, а власний hex-фон замінюється фоном теми.",
        "Expanded background:": "Фон розгорнутої панелі:",
        "Fill the big panel (the compact capsule stays transparent)": "Заповнювати велику панель (компактна капсула лишається прозорою)",
        "Background color:": "Колір фону:",
        "Custom background (hex):": "Власний фон (hex):",
        "Background opacity:": "Непрозорість фону:",
        "Border:": "Рамка:",
        "Show a subtle outline": "Показувати тонкий контур",
        "Accent color:": "Акцентний колір:",
        "Custom accent (hex):": "Власний акцент (hex):",
        "Idle dot color:": "Колір точки простою:",
        "Sharing dot color:": "Колір точки демонстрації:",
        "Compact order:": "Порядок у компактному вигляді:",
        "Content · Time · FPS": "Вміст · Час · FPS",
        "Time · Content · FPS": "Час · Вміст · FPS",
        "Content · FPS · Time": "Вміст · FPS · Час",
        "FPS · Content · Time": "FPS · Вміст · Час",
        "Time · FPS · Content": "Час · FPS · Вміст",
        "FPS · Time · Content": "FPS · Час · Вміст",
        "Separators:": "Розділювачі:",
        "Show “/” dividers between modules": "Показувати розділювачі “/” між модулями",
        "“Content” is the active item — music, language, notification, download or status. Time and the FPS counter can be placed before or after it.": "“Вміст” — активний елемент: музика, мова, сповіщення, завантаження або стан. Час і лічильник FPS можна розмістити до або після нього.",
        "Distance from panel:": "Відстань від панелі:",
        "Gap between the small capsule and the big expanded panel. Increase it if the panel appears too close to or overlapping the capsule.": "Проміжок між малою капсулою та великою розгорнутою панеллю. Збільште його, якщо панель надто близько або перекриває капсулу.",
        "Music": "Музика",
        "Notification": "Сповіщення",
        "Keyboard layout": "Розкладка клавіатури",
        "Download active": "Триває завантаження",
        "Downloads": "Завантаження",
        "Sharing screen": "Демонстрація екрана",
        "Build succeeded": "Збірку виконано",
        "Build failed": "Збірка не вдалася",
        "No title": "Без назви",
        "Media player": "Медіаплеєр",
        "%1 unread": "%1 непрочитано",
        "New notification": "Нове сповіщення",
        "Volume": "Гучність",
        "Pomodoro session in progress": "Сеанс Pomodoro триває",
        "%1% complete": "Виконано %1%",
        "No active downloads": "Немає активних завантажень",
        "Connected": "Підключено",
        "Active capture or presentation mode": "Активне захоплення або режим презентації",
        "success": "успіх",
        "failed": "помилка",
        "Status": "Стан"
    }
};

function language() {
    var name = "en";
    try {
        name = Qt.locale().name.toLowerCase().replace("_", "-");
    } catch (error) {
        return "en";
    }

    if (name.indexOf("zh") === 0) {
        return "zh";
    }

    var shortName = name.split("-")[0];
    return translations[shortName] ? shortName : "en";
}

function t(source) {
    var lang = language();
    return translations[lang] && translations[lang][source] ? translations[lang][source] : source;
}

function tr(source, value) {
    return t(source).replace("%1", value);
}
